#
# This is the YAML version of workflow.js
#

development:
  # Open the browser to specified location when the application starts
  open: '#'
  host: 127.0.0.1
  port: 3000
  historyFallback: true
  notifications: true
  # Enable hot reloading server. Note that only changes
  # to CSS are currently hot reloaded. JS changes will refresh the browser.
  hot: true

ekko:
  host: 127.0.0.1
  port: 9999
  plugins:
    - availity-mock-data
  pluginContext: http://localhost:3000/api
  enabled: true

proxies:
  - context: /api
    target: 'http://localhost:9999'
    enabled: true
    pathRewrite:
      '^/api': ''
    headers:
      RemoteUser: jsmith



