sudo: false
language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
notifications:
  email: false
env:
  global:
    - secure: 7JHHQ+vC3caJErCHryzUdoypofISbLYdv7HxkfE9sEvND36XvZKW64WfJ+9GAfyu4QAmWmcMa1cJXwu3/ugRtBkMtpA4WBSlKGh+11O6IkyKAz4Ec0cN2h1S9B9kHoqWJQ/54OFUsIDHleJa3ZL+z57s/mDtebpKsF1/12lWJm6+FAyrW5Xyf8PSB4tjp9A7mNaObOVb2+lLIXPtnl52sgHeVdAdugfinhRPwSbXUnQaJE5jf8RFTYhxd5P5HrPwh2QbIy2h7hi5hby1+Pd/JeYMwUJakZBSSJypDwBGwF2QCgVMWoBGlW8bpBDriy5ExWFFXYQGLm+Hy79t8irVzeNVO0JmIlQSkf4DCfExdU1UtSgNPyfTQ05U1bMggpBMextUWUtPZaxhuGGU3gy8/Kh09tUQ+Fa7iG7PPobILEF+yu/WK+U5QEujOILtWOjVvidrKMeK7JUC6NAU3eti1yGTv0qTNqe6n7WVnf9hYZl9OloW0UdICb+J9y1giyOvgPxLT9H1FrCH2X8gm7l69j8pk6nJLQ6e3OGO+BaW0myYhfpDUN+gpmNoEQnqJZGOQ8uycFrAkUWIS/rs/mki4rRrevPfAT5RlzDPCza0SRkcZxw0nAFxtBtZhMncWLQm/60CpPUn/uJWNEzQ4FPnPoU4ZsEhKZW0tHaTl5WG1lA=
    - secure: c7N/PjfDXsMtDu3lSJ3F93Lrn3ktRkAZZ+0uPQ71J06LGH710qavlGwglxmxWHyMvDe6Ho6ZXAVt49/QRHB5siaScXk8kS3NJs2qVYg0IOPub30NUzTYtMEpaHQVIzehH1BN90H+Yo1nTZQLMJxnSTu9nrMbvAlwsuw/AJdDG9NRaGoOiuf5VOCGe+WxzDAkDcmatQFPZ6Yv1cT7OBAMYjx7msHEXM6t2+gzZEaOQcEy0onAC7klMi4WGADDN4tWZI3zQCufOregEhJIT9nw1Gv6UohjaT2o64C37F34zhTPjZH/qpcrfLpBAKWvlFQccbZ6r52tzFhCwn7JNU5atrNjXmAK+JYuKdm4L93HrhPa8lOWHXZpu0QlKaMOB4UwEkieFaI+GnX1fQPftlzBwm3GiYbxRLdYN4hu70l/ghQFtOpq6WMguVf1ADWKBPUBSLDa/1YttELbsGtpybn0JNlP+5EcywsYHq9JBwRJ9ICsIHfcTeCffjgf7/g4xjBs1WN9DSVmXqEwlFeZsYfB9VH2ZIjf9CLvLyA5ktUMRZUeiMd2DrLzG/6FmzEzOyhBifrrTViGeiRzw0Pl05RZDo7ebF0ZaN0meUVUJTvRuS9G2FSWvcOiTe3AMro4tF1Nqrtke+8GyFsGF+gdY4jPgBAn7e0Si+Fq9KaybzYhuKk=
addons:
  sauce_connect: true
  jwt:
    secure: BQv5ubXtDx+qTz6eBtw7vWGUaJPCjNl4S2gDsxjWM58G5KHiLz9O4UDzJRsunHI9hpLuH3fB4chNt1RwgPQ11PwENBJCE2PFS+kT/7EF5qjXwI6ZEXbt/dfuEtZehgEtWtMVutVuhqq6ctvNKzTcAF+WSnOHTjVG6RvEQoj1BxwZDAMwMwXPzQp8gZT2deOsQIELiQEDqW5BB6X+CHZIkUSjc5cUSpmIe5ov5yuP/HSweH9454ErfBiV81vQgveJT5dKN1wjZilkAfusehHtIzXz9ws4jDlcWAnt/NUoFaxOonRO7+uWVtCP/WUQMjlUy7Gz1THMs9x8Ml+DOxLPHQTXtIIsryYZjgWUZG8RWV3Rpjd3nQzPjo8HjMjlxPBAk7fjzFptuOAeDn6L0WQvqopzRy1Q2N0xZvZU1jmlRfIYylHRiTq/mz61JE4nc03GrQ70Z6/RjG8b8mmxxEcAB5jAwlHuyxroctCWwWHVrha5MwxZ9CUI+ySRWJO5xrddWthzsHj3f6gVFnynWz/EHspV5KU+SmujW4mShJCvMjZUNbuO3F0WIFOFE70I24YyjOp37wp345QUeYlJKcuLHCwUuAMOXjv04IMZzF56ukEs8OgbGHVLJZC50rNZf+tlCEEWBorQGymhzT0c+sp4YMkUi0QhWhshNg0om8FvagM=
git:
  depth: 1
matrix:
  fast_finish: true
before_script:
  - lerna bootstrap
script:
  - lerna run lint
  - learn run test:integration
