approvedGitRepositories:
  - "**"

changesetIgnorePatterns:
  - "**/*.test.{js,ts}"
  - "**/*.spec.{js,ts}"
  - "**/*.{md,mdx}"
  - "**/yarn.lock"
  - .yarnrc.yml
  - .yarn/**/*

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
