yarnPath: .yarn/releases/yarn-3.0.2.cjs

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
