
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Setup Dependencies
          command: yarn install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: # LInt
          name: Run Lint
          command: |
            yarn lint
      - run: # Test
          name: Run Test
          command: |
            yarn test
      - run:
          name: Run App Build
          command: |
            yarn run build:app
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Setup Dependencies
          command: yarn install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Authenticate
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            git config --global user.email $GITHUB_EMAIL
            git config --global user.name $GITHUB_USER
      - run: # Test
          command: |
            yarn release:ci
            yarn deploy:docs
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          context: availity-deploy
      - deploy:
          context: availity-deploy
          requires:
            - build
          filters:
            branches:
              only: master
