---
#
# 0 - disable
#     Rules that more harmful than useful, or just buggy.
#
# 1 - warning
#     Rules that we didn't encounter yet. You can safely ignore them,
#     but I'd like to know any interesting use-cases they forbid.
#
# 2 - error
#     Rules that have proven to be useful, please follow them.
#

# https://github.com/Availity/eslint-config-availity/browser
extends: availity/browser
rules:
  import/no-unresolved: 0
  import/no-extraneous-dependencies: 0
  import/extensions: 0
globals:
  app-module: false
