name: Artifactory Check CI

on:
  push:
    branches: [master]
  pull_request:
    types:
      - opened
      - synchronize
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Checkout shared Availity tools
        uses: actions/checkout@v3
        with:
          repository: Availity/.github
          token: ${{ secrets.BOT_TOKEN }}
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: tools

      - name: Run registry checker
        working-directory: tools
        run: ./scripts/artifactory-check.sh
