# This workflow has access to secrets and a read token
name: Dependabot Build
on:
  workflow_run:
    workflows: ['Dependabot PR Check']
    types:
      - completed

permissions: write-all # TODO: figure out appropriate permissions

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [12, 14, 16]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Restore yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Check Constraints
        run: yarn constraints

      - name: Lint
        run: yarn lint

      - name: Unit Test
        run: yarn test

      - name: Integration Test
        run: yarn test:integration
