# This workflow doesn't have access to secrets and has a read-only token
# sh-like shells exit with the exit code of the last command executed in a script,
# which is also the default behavior for actions.
# The runner will report the status of the step as fail/succeed based on this exit code,
# and this code can be used to conditionally run other workflows
name: Dependabot PR Check
on: push

jobs:
  check-dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - run: echo "PR created by Dependabot"
