# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn test:app
      - run: yarn build:docs
      - name: Deploy draft to Netlify
        uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_DEPLOY_KEY }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_API_ID }}
          build-dir: docusaurus/build
          draft: true
          comment-on-commit: true
